future: false
markdown: rdiscount
highlighter: true
permalink: /post/:year/:month/:title
paginate: 3

sass:
  sass_dir: assets/css
  style: :nested

exclude: ["node_modules", "README.md", "package.json", ".gitignore", "gulpfile.js"]